In [1]:
import pandas as pd
import numpy as np
import os
import torch
import sys
from tqdm import tqdm
sys.path.append('..')
from utils.utils import colorize_mask, latent_to_image, oht_to_scalar
import pickle
from label_model import prepare_stylegan
device = "cuda:1"

In [2]:
few_shot_classes = {"Nofinding": 0,
    'NoduleMass': 1,
    'Infiltration': 2,
    'LungOpacity': 3,
    'Consolidation': 4,
    'Pleuralthickening': 5,
    'ILD': 6,
    'Cardiomegaly': 7,
    'Pulmonaryfibrosis': 8,
    'Aorticenlargement': 9,
    'Otherlesion': 10,
    'Pleuraleffusion': 11,
    'Calcification': 12,
    'Atelectasis': 13,
    'Pneumothorax': 14}
args = {'exp_dir': 'results_dir_multitask_generation', 'batch_size': 1, 'category': 'xray', 'debug': False, 'dim': [1024, 1024, 5088], 'deeplab_res': 1024, 'number_class': 2, 'testing_data_number_class': 2, 'number_class_classification': 15, 'classification_channels': 16, 'classification_map_size': 16, 'annotation_image_path_classification': '/home/jessica/labelGAN/Image2StyleGAN/images/generated_latents_from_class_distr/', 'max_training': 7, 'stylegan_ver': '1', 'annotation_data_from_w': False, 'annotation_mask_path': './generations', 'testing_path': '', 'average_latent': './generations/avg_latent_stylegan1.npy', 'annotation_image_latent_path': './generations/latent_stylegan1.npy', 'annotation_image_latent_path_classification': '/home/jessica/labelGAN/Image2StyleGAN/images/generated_latents_from_class_distr', 'stylegan_checkpoint': '/home/jessica/mountdir/data/labelGAN/checkpoints/styleGAN/GAN_GEN_8.pth', 'model_num': 1, 'upsample_mode': 'bilinear'}

In [3]:
g_all, avg_latent, upsamplers = prepare_stylegan(args, device)

In [4]:
image_names_classification = os.listdir(args['annotation_image_path_classification'])
mask = ["tophat" not in elem for elem in image_names_classification]
image_names_classification = np.array(image_names_classification)[mask]
affine_layers_list = []
labels = []

In [10]:
i

170

In [12]:
if not os.path.isfile("./affine_layers_list.pkl"):
        i = 0
        for x in tqdm(image_names_classification): 
            if i <= 170: 
                i+=1 
                continue
            i+=1 
            im_name = os.path.join(args['annotation_image_path_classification'], x)
            label = torch.tensor([few_shot_classes[x.split("_")[0]]])
            latent_input = torch.tensor(np.load(im_name)).type(torch.FloatTensor).to(device).squeeze()
            img, feature_maps, style_latents, affine_layers = latent_to_image(g_all, upsamplers, latent_input.unsqueeze(0), dim=args['dim'][1],
                                            return_upsampled_layers=True, use_style_latents=True, device=device)
            affine_layers_list.extend([elem.cpu().detach()for elem in affine_layers])
            labels.extend([label] * len(affine_layers))

 71%|███████   | 215/304 [04:30<09:04,  6.12s/it]

In [8]:
len(affine_layers_list), len(labels)

(3042, 3042)

In [9]:
if not os.path.isfile("./affine_layers_list_2.pkl"): 
        with open('./affine_layers_list_2.pkl', 'wb') as f:
            pickle.dump(affine_layers_list, f)
        with open('./affine_layers_labels_2.pkl', 'wb') as f:
            pickle.dump(labels, f)
else:
        file = open("./affine_layers_list_2.pkl",'rb')
        file1 = open("./affine_layers_labels_2.pkl",'rb')
        affine_layers_list = pickle.load(file)
        labels = pickle.load(file1)

In [11]:
sg = np.load('./generations/latent_stylegan1.npy')

In [17]:
np.save('./generations/latent_stylegan1_small.npy', sg[0:7])

In [8]:
a

(99, 512)

In [3]:
few_shot_classes = {"Nofinding": 0,
    'NoduleMass': 1,
    'Infiltration': 2,
    'LungOpacity': 3,
    'Consolidation': 4,
    'Pleuralthickening': 5,
    'ILD': 6,
    'Cardiomegaly': 7,
    'Pulmonaryfibrosis': 8,
    'Aorticenlargement': 9,
    'Otherlesion': 10,
    'Pleuraleffusion': 11,
    'Calcification': 12,
    'Atelectasis': 13,
    'Pneumothorax': 14}

In [16]:
p = "/home/jessica/labelGAN/Image2StyleGAN/images/generated_latents_from_class_distr/"
image_names_classification = os.listdir(p)
mask = ["tophat" not in elem for elem in image_names_classification]
image_names_classification = np.array(image_names_classification)[mask]
affine_layers_list = []
labels = []
if not os.path.isfile("./affine_layers_labels.pkl"):
    for x in image_names_classification:
        im_name = os.path.join(p, x)
        label = torch.tensor([few_shot_classes[x.split("_")[0]]])
        labels.extend([label] * 9)
if not os.path.isfile("./affine_layers_labels.pkl"):
    with open('affine_layers_labels.pkl', 'wb') as f:
        pickle.dump(labels, f)
file1 = open("affine_layers_labels.pkl",'rb')
label1 = pickle.load(file1)

In [18]:
label1

[tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 ten