In [4]:
import pandas as pd
import numpy as np
import os
import torch
import pickle

In [11]:
sg = np.load('./generations/latent_stylegan1.npy')

In [17]:
np.save('./generations/latent_stylegan1_small.npy', sg[0:7])

In [8]:
a

(99, 512)

In [3]:
few_shot_classes = {"Nofinding": 0,
    'NoduleMass': 1,
    'Infiltration': 2,
    'LungOpacity': 3,
    'Consolidation': 4,
    'Pleuralthickening': 5,
    'ILD': 6,
    'Cardiomegaly': 7,
    'Pulmonaryfibrosis': 8,
    'Aorticenlargement': 9,
    'Otherlesion': 10,
    'Pleuraleffusion': 11,
    'Calcification': 12,
    'Atelectasis': 13,
    'Pneumothorax': 14}

In [16]:
p = "/home/jessica/labelGAN/Image2StyleGAN/images/generated_latents_from_class_distr/"
image_names_classification = os.listdir(p)
mask = ["tophat" not in elem for elem in image_names_classification]
image_names_classification = np.array(image_names_classification)[mask]
affine_layers_list = []
labels = []
if not os.path.isfile("./affine_layers_labels.pkl"):
    for x in image_names_classification:
        im_name = os.path.join(p, x)
        label = torch.tensor([few_shot_classes[x.split("_")[0]]])
        labels.extend([label] * 9)
if not os.path.isfile("./affine_layers_labels.pkl"):
    with open('affine_layers_labels.pkl', 'wb') as f:
        pickle.dump(labels, f)
file1 = open("affine_layers_labels.pkl",'rb')
label1 = pickle.load(file1)

In [18]:
label1

[tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([6]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([0]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([2]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([8]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([7]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([10]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 tensor([13]),
 ten